name: Deploy Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 5 * *"

# https://ashishb.net/tech/common-pitfalls-of-github-actions/
jobs:
  build_and_deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 20
          cache: "npm"
      - name: Build
        run: |
          npm ci
          cd ./functions && npm ci && cd ..
          npm run test:unit
          npm run build
      - name: Setup Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{secrets.FIREBASE_SERVICE_ACCOUNT_PROD}}"
      - name: Deploy
        run: |
          npm i -g firebase-tools@latest
          firebase deploy --project prod --json
