name: Preview Prod

on:
  pull_request_target:
    branches:
      - main

jobs:
  build_and_preview_website:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Check out the pull request HEAD
          node-version: 18
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          npm ci
          cd ./functions && npm ci && cd ..
          npm run test:unit
          npm run build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          node-version: 18
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}"
          projectId: dvc-rofr-stats
